*~
*pyc
*.DS_Store
*.egg
*.eggs
*.egg-info
*.log
*.pyc
*.sass-cache
*build/
*dat
.env
venv
.pytest_cache/
.ipynb_checkpoints
.ruby-version
.tox
.pytype
dist/
pip-wheel-metadata
docs/nlu/_build
docs/_build
*.db
scala/
mongodb/
.cache/
build
build/
*.egg-info/
jnk/
logs/
tmp/
profile.*
*.sqlite
lastmile_ai/learn/plots/
*npy
*#
*log.json
.coverage
.coveralls.yml
.idea/
*.iml
out/
_db/
.vscode/
.DS_Store
.mypy_cache/
**/*.tar.gz
**/*.tar
.pytest_cache
test_download.zip
node_modules/
npm-debug.log
.python-version
tokens.dat
.idea
kipp

components/gitlab/gitlab*
__data/


remote: error: branch refs/heads/feature:
remote: To push into this reference you need 'Push' rights.
remote: User: modongsong
remote: Contact an administrator to fix the permissions
remote: Processing changes: refs: 1, done    
To http://gerrit.ai.cmri.cn:29480/gerrit/a/QDLAKE/base/back/jtqdh-datastore-service
 ! [remote rejected] feature -> feature (prohibited by Gerrit: not permitted: update)
error: failed to push some refs to 'http://gerrit.ai.cmri.cn:29480/gerrit/a/QDLAKE/base/back/jtqdh-datastore-service'